---

- name: copy docker-ce.repo
  template: src=docker-ce.repo
      dest=/etc/yum.repos.d/docker-ce.repo
      mode=644

- name: install docker CE version
  yum: name=docker-ce-17.06.0.ce-1.el7.centos state=present

- name: install docker compose
  pip: name=docker-compose
       virtualenv={{ virtualenv_devel }}
  sudo_user: vagrant
