---
# configure redis for any server type
#
# download and install redis stable
#

- name: ensure directory
  file: path=/home/vagrant/src
      state=directory mode=775
      owner={{ project_owner_devel }} group={{ project_group_devel }}

- name: download
  get_url: url=http://download.redis.io/redis-stable.tar.gz
      dest=/home/vagrant/src/redis-stable.tar.gz
  sudo_user: vagrant

- name: unpack
  unarchive: copy=no
      src=/home/vagrant/src/redis-stable.tar.gz
      dest=/home/vagrant/src/
      creates=/home/vagrant/src/redis-stable/README
  sudo_user: vagrant

- name: build
  shell: >
    make
    chdir=/home/vagrant/src/redis-stable
    creates=/home/vagrant/src/redis-stable/src/redis-server
  sudo_user: vagrant

- name: install
  shell: >
    make install
    chdir=/home/vagrant/src/redis-stable
    creates=/usr/local/bin/redis-server

- name: init.d script
  template: src=etc.init.d.redis.j2
      dest=/etc/init.d/redis_6379
      mode=755
      owner=root group=root

- name: etc directory
  file: path=/etc/redis
      state=directory mode=755
      owner=root group=root

- name: conf
  template: src=etc.redis.conf.j2
      dest=/etc/redis/6379.conf
      mode=644
      owner=root group=root

- name: setup service runlevels
  shell: >
    chkconfig --add redis_6379

- name: var directory
  file: path=/var/redis/6379
      state=directory mode=755
      owner=root group=root

- name: start and enable service
  service: name=redis_6379 state=started enabled=yes
