---
- hosts: all
  accelerate: false
  sudo: yes
  gather_facts: false
  vars:
      #deployment_type: 'development'
      #deployment_type: 'development-local'
      deployment_type: 'distribution'

  roles:
      # redhat os
      - base_redhat
      - common
      - postgresql
      - redis
      - appfwk_development
      - appfwk_webserver
      - httpd
      - docker
      - elasticsearch

      # debian/ubuntu os
      #- base_debian
      #- common
      #- mysql
      #- redis
      #- appfwk_development
      #- apache2
      #- appfwk_webserver


  tasks:
      - name: store last provision date
        shell: echo This VM was last provisioned on `date` > /etc/vagrant_last_provisioned

      - name: update motd
        shell: cat /etc/motd.tail /etc/vagrant_last_provisioned > /etc/motd

  handlers:
      - include: handlers.yml
