---
- name: PULL FROM GITHUB TO STAGING AREA
  hosts: all
  accelerate: false
  sudo: yes
  gather_facts: false
  vars_files:
      - vars_common.yml
  vars:
    project_root: "{{ project_root_stage }}"
    project_name: "{{ project_name }}"
    project_repo: "{{ project_repo_stage }}"
    project_owner: "{{ project_owner_stage }}"
    project_group: "{{ project_group_stage }}"
    virtualenv: "{{ virtualenv_stage }}"
    force_checkout: no
    reset: false

  tasks:
      - name: appfwk github checkout with reset
        # used for initial provisioning
        when: reset

        git: repo={{ project_repo }}
           dest={{ project_root }}/{{ project_name }}
           update=yes
           force={{ force_checkout }}
        notify:
        - appfwk static directory
        - update virtualenv
        - install steelscript to virtualenv
        - appfwk bootstrap settings configs
        - appfwk static files
        - appfwk reset and drop users
        - copy production settings
        - copy admin_user
        - appfwk reset and drop users for apache
        - ensure correct appfwk ownership

      - name: appfwk github checkout without reset
        when: not reset

        git: repo={{ project_repo }}
           dest={{ project_root }}/{{ project_name }}
           update=yes
           force={{ force_checkout }}
        notify:
        - appfwk static directory
        - update virtualenv
        - appfwk static files
        - appfwk reset and keep users
        - appfwk reset and keep users for apache
        - ensure correct appfwk ownership

      - meta: flush_handlers

  handlers:
      - include: handlers.yml
