---
# configure apache2 for debian/ubuntu server types

#
# setup apache certificates and SSL
#

#- name: SSL ... make local cert directory
#  file: path=/etc/ssl/localcerts
#      state=directory mode=775
#      owner={{ project_owner_apache }} group={{ project_group_apache }}
#
#- name: SSL ... install local signed cert pem
#  template: src=templates/ssl_apache/selfsignedcerts/apache_local.pem
#      dest=/etc/ssl/localcerts/apache_local.pem
#      mode=600
#      owner=root group=root
#  notify:
#  - restart apache
#
#- name: SSL ... install local signed cert key
#  template: src=templates/ssl_apache/selfsignedcerts/apache_local_nopass.key
#      dest=/etc/ssl/localcerts/apache_local.key
#      mode=600
#      owner=root group=root
#  notify:
#  - restart apache
#
#- name: SSL ... apache - update ports.conf
#  template: src=templates/ssl_apache/ports.conf
#      dest=/etc/apache2/ports.conf
#      mode=664
#      owner=root group=root
#  notify:
#  - restart apache
#
#- name: SSL ... apache - steelscript appfwk site template
#  template: src=templates/ssl_apache/steelscript_appfwk_site_ssl.j2
#      dest=/etc/apache2/sites-available/steelscript_appfwk_site
#      mode=664
#      owner=root group=root
#  notify:
#  - restart apache
#
#
#- name: apache - steelscript appfwk site template - SSL
#  template: src=templates/steelscript_appfwk_site.j2
#      dest=/etc/httpd/conf.d/steelscript_appfwk_site.conf
#      mode=664
#      owner=root group=root
#  notify:
#  - restart apache

#
# setup apache non-SSL
#

- name: apache - steelscript appfwk site template - non-SSL
  template: src=templates/steelscript_appfwk_site_http.j2
      dest=/etc/httpd/conf.d/steelscript_appfwk_site.conf
      mode=664
      owner=root group=root
  notify:
  - restart apache


#
# Configure apache
#

#- name: apache - set apache umask to 002
#  lineinfile:
#      dest=/etc/apache2/envvars
#      line="umask 002"
#      regexp="^umask 002"
#      insertafter=EOF
#      state=present


- name: start and enable apache service
  service: name=httpd state=started enabled=yes
